version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "bedrock-agent-sample"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-EXAMPLE"
s3_prefix = "bedrock-agent-sample"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []